// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: apigrpc.wallet.proto

package apigrpc

import (
	context "context"
	api "github.com/heroiclabs/nakama/v3/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletProviderClient is the client API for WalletProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletProviderClient interface {
	// Authorize a user against the wallet provider.
	AuthorizeWalletProvider(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Query the wallet provider supported chain.
	QueryChainsFromWalletProvider(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*api.ChainResponse, error)
	// Retrieve user wallet address from wallet provider.
	RetrieveAddressFromWalletProvider(ctx context.Context, in *api.AddressRequest, opts ...grpc.CallOption) (*api.AddressResponse, error)
}

type walletProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletProviderClient(cc grpc.ClientConnInterface) WalletProviderClient {
	return &walletProviderClient{cc}
}

func (c *walletProviderClient) AuthorizeWalletProvider(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/nakama.api.WalletProvider/AuthorizeWalletProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletProviderClient) QueryChainsFromWalletProvider(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*api.ChainResponse, error) {
	out := new(api.ChainResponse)
	err := c.cc.Invoke(ctx, "/nakama.api.WalletProvider/QueryChainsFromWalletProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletProviderClient) RetrieveAddressFromWalletProvider(ctx context.Context, in *api.AddressRequest, opts ...grpc.CallOption) (*api.AddressResponse, error) {
	out := new(api.AddressResponse)
	err := c.cc.Invoke(ctx, "/nakama.api.WalletProvider/RetrieveAddressFromWalletProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletProviderServer is the server API for WalletProvider service.
// All implementations must embed UnimplementedWalletProviderServer
// for forward compatibility
type WalletProviderServer interface {
	// Authorize a user against the wallet provider.
	AuthorizeWalletProvider(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Query the wallet provider supported chain.
	QueryChainsFromWalletProvider(context.Context, *emptypb.Empty) (*api.ChainResponse, error)
	// Retrieve user wallet address from wallet provider.
	RetrieveAddressFromWalletProvider(context.Context, *api.AddressRequest) (*api.AddressResponse, error)
	mustEmbedUnimplementedWalletProviderServer()
}

// UnimplementedWalletProviderServer must be embedded to have forward compatible implementations.
type UnimplementedWalletProviderServer struct {
}

func (UnimplementedWalletProviderServer) AuthorizeWalletProvider(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeWalletProvider not implemented")
}
func (UnimplementedWalletProviderServer) QueryChainsFromWalletProvider(context.Context, *emptypb.Empty) (*api.ChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryChainsFromWalletProvider not implemented")
}
func (UnimplementedWalletProviderServer) RetrieveAddressFromWalletProvider(context.Context, *api.AddressRequest) (*api.AddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveAddressFromWalletProvider not implemented")
}
func (UnimplementedWalletProviderServer) mustEmbedUnimplementedWalletProviderServer() {}

// UnsafeWalletProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletProviderServer will
// result in compilation errors.
type UnsafeWalletProviderServer interface {
	mustEmbedUnimplementedWalletProviderServer()
}

func RegisterWalletProviderServer(s grpc.ServiceRegistrar, srv WalletProviderServer) {
	s.RegisterService(&WalletProvider_ServiceDesc, srv)
}

func _WalletProvider_AuthorizeWalletProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletProviderServer).AuthorizeWalletProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nakama.api.WalletProvider/AuthorizeWalletProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletProviderServer).AuthorizeWalletProvider(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletProvider_QueryChainsFromWalletProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletProviderServer).QueryChainsFromWalletProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nakama.api.WalletProvider/QueryChainsFromWalletProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletProviderServer).QueryChainsFromWalletProvider(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletProvider_RetrieveAddressFromWalletProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletProviderServer).RetrieveAddressFromWalletProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nakama.api.WalletProvider/RetrieveAddressFromWalletProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletProviderServer).RetrieveAddressFromWalletProvider(ctx, req.(*api.AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletProvider_ServiceDesc is the grpc.ServiceDesc for WalletProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nakama.api.WalletProvider",
	HandlerType: (*WalletProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeWalletProvider",
			Handler:    _WalletProvider_AuthorizeWalletProvider_Handler,
		},
		{
			MethodName: "QueryChainsFromWalletProvider",
			Handler:    _WalletProvider_QueryChainsFromWalletProvider_Handler,
		},
		{
			MethodName: "RetrieveAddressFromWalletProvider",
			Handler:    _WalletProvider_RetrieveAddressFromWalletProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apigrpc.wallet.proto",
}
