// tslint:disable
/* Code generated by openapi-gen-angular/main.go. DO NOT EDIT. */

import { Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';

/** Get avaliable features response. */
export interface Features {
	features?:Array<FeaturesFEATURE>
}

export enum FeaturesFEATURE {
  EMAIL_VERIFICATION = 0,
  VERIFICATION_CODE = 1,
}

/** Submit a email verification request. */
export interface SendEmailVerificationRequest {
  // The email address.
	email?:string
}

/** Submit a password reset request. */
export interface SendPasswordResetEmailRequest {
  // The email to reset.
	email?:string
}

/** Verfiy password after verfied. */
export interface VerifyPasswordRenewalRequest {
  // The renewed password.
	password?:string
  // The user credentials.
	token?:string
}

const DEFAULT_HOST = 'http://127.0.0.1:7120';
const DEFAULT_TIMEOUT_MS = 5000;

export class ConfigParams {
  host!: string
  timeoutMs!: number
}

@Injectable({providedIn: 'root'})
export class ApplicationService {
	private readonly config;

  constructor(private httpClient: HttpClient, @Optional() config: ConfigParams) {
    const defaultConfig: ConfigParams = {
      host: DEFAULT_HOST,
      timeoutMs: DEFAULT_TIMEOUT_MS,
    };
    this.config = config || defaultConfig;
  }

  /** Verfiy password from web ui. */
  verifyPasswordRenewal(auth_token: string, body: VerifyPasswordRenewalRequest): Observable<any> {
		const urlPath = `/v2/account/password/renew`;
    let params = new HttpParams();
    return this.httpClient.post(this.config.host + urlPath, body, { params: params, headers: this.getTokenAuthHeaders(auth_token) })
  }

  /** Send password reset email. */
  sendPasswordResetEmail(auth_token: string, body: SendPasswordResetEmailRequest): Observable<any> {
		const urlPath = `/v2/account/password/reset`;
    let params = new HttpParams();
    return this.httpClient.post(this.config.host + urlPath, body, { params: params, headers: this.getTokenAuthHeaders(auth_token) })
  }

  /** Send email verification. */
  sendEmailVerificationCode(auth_token: string, body: SendEmailVerificationRequest): Observable<any> {
		const urlPath = `/v2/account/verify/code`;
    let params = new HttpParams();
    return this.httpClient.post(this.config.host + urlPath, body, { params: params, headers: this.getTokenAuthHeaders(auth_token) })
  }

  /** Send email verification. */
  sendEmailVerificationLink(auth_token: string, body: SendEmailVerificationRequest): Observable<any> {
		const urlPath = `/v2/account/verify/link`;
    let params = new HttpParams();
    return this.httpClient.post(this.config.host + urlPath, body, { params: params, headers: this.getTokenAuthHeaders(auth_token) })
  }

  /** Verfiy email address from web ui. */
  verifyEmailAddress(auth_token: string, token: string): Observable<any> {
		token = encodeURIComponent(String(token))
		const urlPath = `/v2/account/verify/${token}`;
    let params = new HttpParams();
    return this.httpClient.delete(this.config.host + urlPath, { params: params, headers: this.getTokenAuthHeaders(auth_token) })
  }

  /** Get available features from web ui. */
  getFeatures(auth_token: string): Observable<Features> {
		const urlPath = `/v2/features`;
    let params = new HttpParams();
    return this.httpClient.get<Features>(this.config.host + urlPath, { params: params, headers: this.getTokenAuthHeaders(auth_token) })
  }

  private getTokenAuthHeaders(token: string): HttpHeaders {
    return new HttpHeaders().set('Authorization', 'Bearer ' + token);
  }

  private getBasicAuthHeaders(username: string, password: string): HttpHeaders {
    return new HttpHeaders().set('Authorization', 'Basic ' + btoa(username + ':' + password));
  }
}
