// Copyright 2023 Deflinhec
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: web.api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Features_FEATURE int32

const (
	Features_EMAIL_VERIFICATION Features_FEATURE = 0
	Features_VERIFICATION_CODE  Features_FEATURE = 1
)

// Enum value maps for Features_FEATURE.
var (
	Features_FEATURE_name = map[int32]string{
		0: "EMAIL_VERIFICATION",
		1: "VERIFICATION_CODE",
	}
	Features_FEATURE_value = map[string]int32{
		"EMAIL_VERIFICATION": 0,
		"VERIFICATION_CODE":  1,
	}
)

func (x Features_FEATURE) Enum() *Features_FEATURE {
	p := new(Features_FEATURE)
	*p = x
	return p
}

func (x Features_FEATURE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Features_FEATURE) Descriptor() protoreflect.EnumDescriptor {
	return file_web_api_proto_enumTypes[0].Descriptor()
}

func (Features_FEATURE) Type() protoreflect.EnumType {
	return &file_web_api_proto_enumTypes[0]
}

func (x Features_FEATURE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Features_FEATURE.Descriptor instead.
func (Features_FEATURE) EnumDescriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{2, 0}
}

// Submit a password reset request.
type SendPasswordResetEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The email to reset.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendPasswordResetEmailRequest) Reset() {
	*x = SendPasswordResetEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPasswordResetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailRequest) ProtoMessage() {}

func (x *SendPasswordResetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailRequest.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{0}
}

func (x *SendPasswordResetEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Submit a email verification request.
type SendEmailVerificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The email address.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendEmailVerificationRequest) Reset() {
	*x = SendEmailVerificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailVerificationRequest) ProtoMessage() {}

func (x *SendEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*SendEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Get avaliable features response.
type Features struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []Features_FEATURE `protobuf:"varint,1,rep,packed,name=features,proto3,enum=nakama.web.Features_FEATURE" json:"features,omitempty"`
}

func (x *Features) Reset() {
	*x = Features{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{2}
}

func (x *Features) GetFeatures() []Features_FEATURE {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_web_api_proto protoreflect.FileDescriptor

var file_web_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x65, 0x62, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x6e, 0x61, 0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x77, 0x65, 0x62, 0x22, 0x35, 0x0a, 0x1d, 0x53,
	0x65, 0x6e, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x34, 0x0a, 0x1c, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x7e, 0x0a, 0x08, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6e, 0x61, 0x6b, 0x61, 0x6d, 0x61, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x46, 0x45, 0x41,
	0x54, 0x55, 0x52, 0x45, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x38,
	0x0a, 0x07, 0x46, 0x45, 0x41, 0x54, 0x55, 0x52, 0x45, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x4d, 0x41,
	0x49, 0x4c, 0x5f, 0x56, 0x45, 0x52, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x56, 0x45, 0x52, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x42, 0x63, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e,
	0x68, 0x65, 0x72, 0x6f, 0x69, 0x63, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x6e, 0x61, 0x6b, 0x61, 0x6d,
	0x61, 0x2e, 0x77, 0x65, 0x62, 0x42, 0x09, 0x4e, 0x61, 0x6b, 0x61, 0x6d, 0x61, 0x57, 0x65, 0x62,
	0x50, 0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68,
	0x65, 0x72, 0x6f, 0x69, 0x63, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6e, 0x61, 0x6b, 0x61, 0x6d, 0x61,
	0x2f, 0x76, 0x33, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0xaa, 0x02, 0x0f, 0x4e, 0x61,
	0x6b, 0x61, 0x6d, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_api_proto_rawDescOnce sync.Once
	file_web_api_proto_rawDescData = file_web_api_proto_rawDesc
)

func file_web_api_proto_rawDescGZIP() []byte {
	file_web_api_proto_rawDescOnce.Do(func() {
		file_web_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_api_proto_rawDescData)
	})
	return file_web_api_proto_rawDescData
}

var file_web_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_web_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_web_api_proto_goTypes = []interface{}{
	(Features_FEATURE)(0),                 // 0: nakama.web.Features.FEATURE
	(*SendPasswordResetEmailRequest)(nil), // 1: nakama.web.SendPasswordResetEmailRequest
	(*SendEmailVerificationRequest)(nil),  // 2: nakama.web.SendEmailVerificationRequest
	(*Features)(nil),                      // 3: nakama.web.Features
}
var file_web_api_proto_depIdxs = []int32{
	0, // 0: nakama.web.Features.features:type_name -> nakama.web.Features.FEATURE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_web_api_proto_init() }
func file_web_api_proto_init() {
	if File_web_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPasswordResetEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEmailVerificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_api_proto_goTypes,
		DependencyIndexes: file_web_api_proto_depIdxs,
		EnumInfos:         file_web_api_proto_enumTypes,
		MessageInfos:      file_web_api_proto_msgTypes,
	}.Build()
	File_web_api_proto = out.File
	file_web_api_proto_rawDesc = nil
	file_web_api_proto_goTypes = nil
	file_web_api_proto_depIdxs = nil
}
