name: buf-push
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:

          input: "bcasino"

      - uses: bufbuild/buf-breaking-action@v1
        with:

          input: "bcasino"

          # The 'master' branch of the GitHub repository that defines the module.
          # Note we specify the subdir to compare against.
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=bcasino"
      - uses: bufbuild/buf-push-action@v1
        with:

          input: "bcasino"

          buf_token: ${{ secrets.BUF_TOKEN }}
